### ISSUE TITLE
Geohax doesn't seem to implement the Geohash algorithm??

### ISSUE THREAD

**Issue by ewildgoose** [evuez/geohax#3]
The example shows this:
      iex> Geohax.encode(-132.83, -38.1033, 6)
      "311x1r"
But checking here 
  http://www.movable-type.co.uk/scripts/geohash.html
shows that the answer should be:
  50hbhb

I tested this also with another geohash library...

The same problem appears in the tests:
https://github.com/evuez/geohax/blob/ac7ddfb1b03404b16e5c9d73557f653a540032fd/test/geohax_test.exs#L6

Don't have a problem with a different algorithm, but I think you should clearly explain that it's different? (or is it a bug?)

**Comment by evuez** [comment]
It's actually the same algorithm, but `Geohax.encode/3` excepts the longitude first, not the latitude. I should try to emphasize that in the README!

Keeping this open until I update the README.

**Comment by evuez** [comment]
@ewildgoose updated the README to make this clearer :slightly_smiling_face:
